version: "3"

services:
  bitcoinz-insight-patched:
    image: btcz/bitcoinz-insight-patched:1.2.1
    networks:
      - back
    restart: always
    ports:
      - 1989:1989
    volumes:
      - ./data/:/bitcoinz/data
      - ./bitcoinz.conf:/bitcoinz/data/bitcoinz.conf
  insight:
    build:
      context: .
    networks:
      - back
    restart: always
    ports:
      - 3001:3001
    volumes:
      - ./bitcore-node.json:/usr/src/app/btcz-explorer/bitcore-node.json

networks:
  back:
